### PR TITLE
Use mq react to manage Queue to load URLs

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/dpovshed/octopus/issues/17

This abstracts a big amount of complexity "away" in an existing component.

### CODE REVIEW

**Review by dpovshed — APPROVED** [review]
Well, changes are huge, but it looks good enough!

I haven't tested it, just reviewed the code changes, it seems good to go.

**Comment by holtkamp** [comment]
I noticed (initial) memory consumption increases significantly. 
https://github.com/clue/reactphp-mq/issues/13

I will keep an eye on this, there is no hurry in merging. Maybe it is better to also keep the "old" approach alive and add the MQ-React Queue as addition... Let's see!

**Comment by dpovshed** [comment]
Alternatively, it can be a new major release 1.0 . 

Since the ability to set SpawnDelay is going to removed, some crazy things may happen - like, all 20-50-70 initial requests will try to get info from server at the exact same time. We do not using spawnDelayMax / spawnDelayMin at the moment, but if needed we can add support quite easily. With a new model - I am not sure how it would work :)

**Comment by holtkamp** [comment]
Yeah indeed, think it is better to re-think this. Closing for now, will restart my work and try to be a bit cleaner.

**Comment by holtkamp** [comment]
>Since the ability to set SpawnDelay is going to removed, some crazy things may happen - like, all 20-50-70 initial requests will try to get info from server at the exact same time.

The amount of initial request would currently be "capped" at the indicated concurrency setting. I use quite low concurrency settings, but indeed, in case a concurrency of 70 is used, this might result in undesired behaviour.

Asked whether this is possible in https://github.com/clue/reactphp-mq/issues/14

**Pull request closed without merging**
